# Generated by Django 3.1.7 on 2021-04-08 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('avatar', models.CharField(default='', max_length=500)),
                ('gender', models.CharField(default='', max_length=20)),
                ('birthday', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.BooleanField(db_index=True, default=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoName', models.CharField(max_length=100)),
                ('image', models.CharField(default='', max_length=500)),
                ('videoType', models.CharField(default='other', max_length=50)),
                ('source', models.CharField(default='custom', max_length=20)),
                ('nation', models.CharField(default='other', max_length=5)),
                ('desc', models.TextField()),
                ('status', models.BooleanField(db_index=True, default=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('videoName', 'videoType', 'source', 'nation')},
            },
        ),
        migrations.CreateModel(
            name='VideoSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('number', models.IntegerField(default=1)),
                ('externalVideo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videoSub', to='app.externalVideo')),
            ],
            options={
                'unique_together': {('externalVideo', 'number')},
            },
        ),
        migrations.CreateModel(
            name='VideoStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('identity', models.CharField(default='', max_length=50)),
                ('externalVideo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videoStar', to='app.externalVideo')),
            ],
            options={
                'unique_together': {('externalVideo', 'name', 'identity')},
            },
        ),
    ]
