# Generated by Django 3.1.7 on 2021-04-08 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('number', models.IntegerField(default=1)),
                ('externalVideo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videoDetail', to='app.externalVideo')),
            ],
            options={
                'unique_together': {('externalVideo', 'number')},
            },
        ),
        migrations.DeleteModel(
            name='VideoSub',
        ),
    ]
