# Generated by Django 3.1.7 on 2021-04-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210408_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetail',
            name='url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
