# Generated by Django 3.1.7 on 2021-04-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210409_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetail',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
